services:
  mysql:
    image: mysql:8.0
    container_name: dyndns-mysql
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD  # root password
      MYSQL_DATABASE: $MYSQL_DATABASE            # databasename
      MYSQL_USER: $MYSQL_USER                    # database user
      MYSQL_PASSWORD: $MYSQL_PASSWORD            # user password
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
  dyndns-app:
    build:
      context: .
    container_name: dyndns-app
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DATABASE_URL: $DYNDNS_DATABASE_URL
      DATABASE_USERNAME: $DYNDNS_DATABASE_USERNAME
      DATABASE_PASSWORD: $DYNDNS_DATABASE_PASSWORD
    volumes:
      - ./config:/app/config
volumes:
  mysql_data:
