duckdns:
  domain: "yourdomain"       # Name of the DuckDNS subdomain, without .duckdns.org
  token: "yourtoken"         # DuckDNS token
  ipDetectionEnabled: true   # Use automatic IP detection (optional)
  ipv6DetectionEnabled: false # Enable IPv6 handling
  verbose: true              # Enable detailed output in responses
  clearRecords: false        # Clear records (optional)

dyndns:
  apiToken: "your_api_token"
  zoneId: "your_zone_id"
  records:
    - name: "subdomain1.example.com"
      recordId: "record_id_1"
    - name: "subdomain2.example.com"
      recordId: "record_id_2"
  checkInterval: 10 # minuti
