database:
  url: "jdbc:mysql://localhost:3306/dyndns"  # JDBC URL for the MySQL database
  username: "your_username"                 # Replace with your database username
  password: "your_password"                 # Replace with your database password
